spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/employeesdb'
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQL5Dialect'
